---
- name: Submit file to Zscaler Cloud Sandbox
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Submit sample.exe to Cloud Sandbox
      zscaler.ziacloud.zia_sandbox_submission:
        file_path: 'sample.exe'
        force: yes
      register: sandbox_response

    - name: Display Cloud Sandbox Response
      debug:
        var: sandbox_response

    - name: Submit file for out-of-band inspection
      zscaler.ziacloud.zia_sandbox_submission:
        file_path: "sample.zip"
        inspection_mode: "out_of_band"
      register: oob_response

    - name: Display Cloud Sandbox Response
      debug:
        var: oob_response.submission_response
