- name: Location Groups
  hosts: localhost
  tasks:
    - name: Gather Information Details of all location groups
      zscaler.ziacloud.zia_location_groups_info:
      register: result
    - debug:
        msg: "{{ result }}"

    - name: Gather Information Details of a location group by name
      zscaler.ziacloud.zia_location_groups_info:
        name: "Corporate User Traffic Group"
      register: result
    - debug:
        msg: "{{ result }}"

    - name: Gather Information Details of a location group by ID
      zscaler.ziacloud.zia_location_groups_info:
        id: 24326827
      register: result
    - debug:
        msg: "{{ result }}"