# - name: Network Services Groups
#   hosts: localhost
#   tasks:
#     - name: Gather information about Network Services Group (all)
#       zscaler.ziacloud.zia_cloud_firewall_network_services_groups_info:
#       register: result
#     - debug:
#         msg: "{{ result }}"

#     - name: Gather information about Network Services Group (by name)
#       zscaler.ziacloud.zia_cloud_firewall_network_services_groups_info:
#         name: "Example"
#       register: result
#     - debug:
#         msg: "{{ result }}"

#     - name: Gather information about Network Services Group (by id)
#       zscaler.ziacloud.zia_cloud_firewall_network_services_groups_info:
#         id: 2355503
#       register: result
#     - debug:
#         msg: "{{ result }}"

#     - name: Create update Network Services Group
#       zscaler.ziacloud.zia_cloud_firewall_network_services_groups:
#         name: "Ansible_Test"
#         description: "Ansible_Test"
#         service_ids:
#           - "ICMP_ANY"
#         state: absent
#       register: result
#     - debug:
#         msg: "{{ result }}"

- name: Network Services Groups
  hosts: localhost
  connection: local
  tasks:
    - name: Gather Network Services Groups
      zscaler.ziacloud.zia_cloud_firewall_network_services_info:
      register: all

    - name: Create/update Network Services Groups
      zscaler.ziacloud.zia_cloud_firewall_network_services_groups:
        name: "Ansible Network Services Group"
        service_ids:
          - '{{ all.data[0].id }}'
          - '{{ all.data[1].id }}'
          - '{{ all.data[2].id }}'
        state: absent
      register: create_nw_svc_group
    - name: Display information about a new Network Services Group
      ansible.builtin.debug:
        msg: "{{ create_nw_svc_group }}"