- name: Security Policy Settings
  hosts: localhost
  tasks:
    - name: Blacklist URL
      zscaler.ziacloud.zia_security_policy_settings:
        urls:
          - test1.acme.com
          - test2.acme.com
          - test3.acme.com
          - test4.acme.com
        url_type: "blacklist"
        state: absent
      register: result
    - debug:
        msg: "{{ result }}"
