- name: Network Services Groups
  hosts: localhost
  tasks:
    - name: Create/update Network Services Groups
      zscaler.ziacloud.zia_fw_network_services_groups:
        name: "Ansible_Test"
        description: "Ansible_Test"
        # services:
        #   - "ICMP_ANY"
        state: absent
      register: result
    - debug:
        msg: "{{ result }}"

    # - name: Gather information about IP Destination Group (by id or name)
    #   zscaler.ziacloud.zia_fw_ip_source_groups_info:
    #     name: Ansible_Test
    #     id: 1175558
    #   register: result
    # - debug:
    #     msg: "{{ result }}"
