name: Ansible Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ansible_lint:
    name: Verify Ansible Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ansible/ansible-lint@v24.2.1
