name: sanity

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  sanity:
    timeout-minutes: 30
    name: Sanity (Ⓐ$${{ matrix.versions.ansible }})
    strategy:
      fail-fast: false
      matrix:
        versions:
          - ansible: "2.14"
            python_ver: "3.11"
          - ansible: "2.15"
            python_ver: "3.11"
          - ansible: "2.16"
            python_ver: "3.11"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./ansible_collections/${{ env.NAMESPACE }}/${{ env.COLLECTION_NAME }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: ./ansible_collections/${{ env.NAMESPACE }}/${{ env.COLLECTION_NAME }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_ver }}
