name: GitHub Pages

on:
  push:
    branches:
      - master  # or main if your default branch is named main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Ensure compatibility with your project requirements

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Generate Documentation
        run: make docs

      - name: Commit and Push Documentation
        run: |
          cd docs/html
          git init
          git add -A
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -m "Update generated documentation"
          git push --force ${{ secrets.GITHUB_TOKEN }} HEAD:gh-pages

      # Optional: Clean up to avoid actions cluttering the repo with generated files
      - name: Clean up Generated Files
        run: |
          rm -rf docs/html
