name: Release

on:
  release:
    types:
      - created

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Install pip
        run: |
          python -m pip install --upgrade pip
          pip install ansible
      - name: Create release artifacts
        run: |
          ansible-galaxy collection build
          ansible-galaxy collection publish *.tar.gz --api-key ${{ secrets.GALAXY_API_KEY }}
      - name: Release artifacts to GitHub
        run: |
          gh release upload $TAG ./zscaler-ziacloud*.tar.gz
        env:
          TAG: ${{ github.event.release.tag_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload to Ansible Automation Hub
        run: |
          cat << EOF > ansible.cfg
          [galaxy]
          server_list = automation_hub, release_galaxy

          [galaxy_server.automation_hub]
          url=${{ secrets.AUTOMATION_HUB_URL }}
          auth_url=${{ secrets.AUTOMATION_HUB_SSO_URL }}
          token=${{ secrets.AUTOMATION_HUB_API_TOKEN }}
          [galaxy_server.release_galaxy]
          url=https://galaxy.ansible.com/
          token=${{ secrets.GALAXY_API_KEY }}
          EOF
          ansible-galaxy collection publish ./zscaler-ziacloud*.tar.gz
        env:
          AAP_KEY: ${{ secrets.AAP_KEY }}
